Integracao mongo db
Vinicius-resende-cin/typescript-git-training pull request #6
Opened 2024-07-29 19:32 UTC by ykarocin

2024-07-29 22:50 UTC, Vinicius-resende-cin requested changes

2024-07-29 22:50 UTC, Vinicius-resende-cin commented on src/components/Tasks.tsx
> +      setTasks([...tasks, newTaskObject]);
Essa linha não é desnecessária?

2024-07-29 22:50 UTC, Vinicius-resende-cin commented on backend/src/controllers/taskListController.js
> +            return response.status(401).json({error: "Não foi encontrado a task para deletar!"});
Aqui não seria melhor retornar um status 204? 401 tem mais relação com autenticação.

2024-07-30 13:53 UTC, ykarocin commented on src/components/Tasks.tsx
> +      setTasks([...tasks, newTaskObject]);
A 23?

2024-07-30 13:58 UTC, ykarocin commented on backend/src/controllers/taskListController.js
> +            return response.status(401).json({error: "Não foi encontrado a task para deletar!"});
Faz sentido, já que o comando é executado, mas o conteúdo solicitado não existe

2024-07-30 15:53 UTC, Vinicius-resende-cin commented on src/components/Tasks.tsx
> +      setTasks([...tasks, newTaskObject]);
Isso

2024-07-30 16:33 UTC, ykarocin commented on src/components/Tasks.tsx
> +      setTasks([...tasks, newTaskObject]);
é verdade, bastaria ser executada depois de gerar o _id, vou alterar

2024-07-30 17:02 UTC, Vinicius-resende-cin approved these changes

2024-07-30 17:20 UTC, merged